IndexRoute:
    path: /
    defaults: { _controller: 'App\Controller\HomeController::indexAction' }


ProjectsRoute:
    path: /photography/
    defaults: { _controller: 'App\Controller\ProjectController::view' }

AboutRoute:
    path: /about/
    defaults: { _controller: 'App\Controller\HomeController::AboutAction' }

GalleryRoute:
        path: /photography/{projectTitle}
        defaults: { _controller: 'App\Controller\PhotoController::GalleryAction' }

AdminProjectsRoute:
    path: /admin/projects
    defaults: { _controller: 'App\Controller\ProjectController::new' }

AdminGalleryRoute:
        path: /admin/photos
        defaults: { _controller: 'App\Controller\PhotoController::new' }