IndexRoute:
    path: /
    defaults: { _controller: 'App\Controller\HomeController::indexAction' }

ProjectsRoute:
    path: /photography/
    defaults: { _controller: 'App\Controller\ProjectController::viewProjects' }

AboutRoute:
    path: /about/
    defaults: { _controller: 'App\Controller\HomeController::AboutAction' }

BooksRoute:
    path: /books/
    defaults: { _controller: 'App\Controller\BookController::index' }

GalleryRoute:
    path: /photography/{project_slug}
    defaults: { _controller: 'App\Controller\PhotoController::ViewProject' }

PhotoRoute:
    path: /photography/{project_slug}/{photo_slug}
    defaults: { _controller: 'App\Controller\PhotoController::ViewPhoto' }

AdminLoginRoute:
    path: /admin
    defaults: { _controller: 'App\Controller\SecurityController::login' }

AdminProjectsRoute:
    path: /admin/projects
    defaults: { _controller: 'App\Controller\ProjectController::adminProjects' }

AdminAddProjectRoute:
    path: /admin/projects/add
    defaults: { _controller: 'App\Controller\ProjectController::newProject' }

AdminProjectsPositionRoute:
    path: /admin/projects/{id}/position/{position}
    defaults: { _controller: 'App\Controller\ProjectController::updateProjectPosition' }

AdminPhotoPositionRoute:
    path: /admin/photos/{id}/position/{position}
    defaults: { _controller: 'App\Controller\PhotoController::updatePosition' }

AdminPhotosRoute:
    path: /admin/projects/{project_slug}
    defaults: { _controller: 'App\Controller\PhotoController::adminPhotos' }

AdminBooksRoute:
    path: /admin/books
    defaults: { _controller: 'App\Controller\BookController::adminBooks' }

AdminAboutRoute:
    path: /admin/about
    defaults: { _controller: 'App\Controller\AboutController::adminAbout' }

project_delete:
    path:     /admin/project/{id}
    defaults: { _controller: App\Controller\ProjectController::deleteProject }
    methods:  [DELETE]

photo_delete:
    path:     /admin/photo/{id}
    defaults: { _controller: App\Controller\PhotoController::delete }
    methods:  [DELETE]

photo_update:
    path:     /admin/photo/{id}/edit
    defaults: { _controller: App\Controller\PhotoController::edit }
    methods:  [POST]

project_update:
    path:     /admin/project/{id}/edit
    defaults: { _controller: App\Controller\ProjectController::edit }
    methods:  [POST]