IndexRoute:
    path: /
    defaults: { _controller: 'App\Controller\HomeController::indexAction' }


ProjectsRoute:
    path: /photography/
    defaults: { _controller: 'App\Controller\ProjectController::viewProjects' }

AboutRoute:
    path: /about/
    defaults: { _controller: 'App\Controller\HomeController::AboutAction' }

GalleryRoute:
        path: /photography/{projectTitle}
        defaults: { _controller: 'App\Controller\ProjectController::ViewGallery' }

AdminProjectsRoute:
    path: /admin/projects
    defaults: { _controller: 'App\Controller\ProjectController::newProject' }

AdminPhotosRoute:
        path: /admin/photos
        defaults: { _controller: 'App\Controller\PhotoController::newPhoto' }