index:
    path: /
    defaults: { _controller: 'App\Controller\HomeController::indexAction' }


meineroute:
    path: /kunden/{customerId}
    defaults: { _controller: 'App\Controller\HomeController::klausAction' }